dist: xenial
language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake xvfb
  - sudo apt-get install -y libgadu3 libgadu-dev
  - sudo apt-get install -y libarchive-dev libotr5-dev libmessaging-menu-dev libqxmpp-dev libmpdclient-dev libenchant-dev libxss-dev libboost-all-dev
  - sudo apt-get install -y qtbase5-dev qttools5-dev-tools qtdeclarative5-dev libqt5webkit5-dev libqt5x11extras5-dev libqt5xmlpatterns5-dev qtscript5-dev qtmultimedia5-dev

before_script:
  - git clone https://github.com/vogel/injeqt.git
  - cd injeqt
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j4
  - make test
  - sudo make install
  - cd ..
  - cd ..
script:
  - sed -i 's/unity_integration/#unity_integration/' Plugins.cmake
  - Xvfb :1 &
  - export DISPLAY=:1
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j4
  - make test

